### ISSUE TITLE
Point3d ConvertTo issue

### ISSUE THREAD

**Issue by ugur1yildiz** [RiSearcher/GeometRi.CSharp#29]
Point3d.ConvertTo doesn't return converted one for globally defined point but Point3d.ToString(Coord3d coord) gives the desired result for a local coordinate 

Can you help about this?

**Comment by ugur1yildiz** [comment]
It is solved, When printing result of Point3d.ConvertTo, Point3d.ToString() method is used that gives string presentation of the point wrt Global Coordinate System.  However  .X / .Y and .Z properties of  Point3d.ConvertTo stores correct coordinartes wrt Local Coordinate System.

**Comment by cyrilpreiss** [comment]
Point3d.ConvertTo still doesn't work.   Point3d.ToString(ccord) is working

**Comment by RiSearcher** [comment]
Hi!
What do you mean by "Point3d.ConvertTo still doesn't work"?
